export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const UPDATE_FILTERS = "UPDATE_FILTERS";

export const FETCH_PLANETS_SUCCESS = "FETCH_PLANETS_SUCCESS";
export const FETCH_PLANETS_FAILURE = "FETCH_PLANETS_FAILURE";

export const FETCH_SHAPE_SUCCESS = "FETCH_SHAPE_SUCCESS";
export const FETCH_SHAPE_FAILURE = "FETCH_SHAPE_FAILURE";

export const FETCH_COLOR_SUCCESS = "FETCH_COLOR_SUCCESS";
export const FETCH_COLOR_FAILURE = "FETCH_COLOR_FAILURE";

export const FETCH_SIZE_SUCCESS = "FETCH_SIZE_SUCCESS";
export const FETCH_SIZE_FAILURE = "FETCH_SIZE_FAILURE";
